name: AWS OIDC Connection Test

on:
  workflow_dispatch: { }

permissions:
  id-token: write
  contents: read

jobs:
  test-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::035934723491:role/GitHubActionsDeployRole
          aws-region: us-east-2

      - name: Verify AWS Identity
        run: |
          echo "Verifying OIDC authentication..."
          aws sts get-caller-identity
